const assets = {
  "LIV Indigo": {
		city: "Sydney", 
    suburb: "Sydney Olympic Park",
    included: ["Free parking", "Free wifi", "Free breakfast", "Free laundry"],
    images: [
      "-/media/Project/Mirvac/LIVMirvac/LIVMirvac/LIVMirvac/images/property-mock/mobile-property.jpg",
      "-/media/Project/Mirvac/LIVMirvac/LIVMirvac/LIVMirvac/images/property-mock/mobile-property.jpg",
      "-/media/Project/Mirvac/LIVMirvac/LIVMirvac/LIVMirvac/images/property-mock/mobile-property.jpg",
    ],
  },
  "LIV Munro": {
		city: "Melbourne", 
    suburb: "Queen Victoria Market",
    included: ["Free parking", "Free wifi", "Free breakfast", "Free laundry"],
    images: [
      "-/media/Project/Mirvac/LIVMirvac/LIVMirvac/LIVMirvac/images/property-mock/mobile-property.jpg",
      "-/media/Project/Mirvac/LIVMirvac/LIVMirvac/LIVMirvac/images/property-mock/mobile-property.jpg",
      "-/media/Project/Mirvac/LIVMirvac/LIVMirvac/LIVMirvac/images/property-mock/mobile-property.jpg",
    ],
  },
};

const apartments = [
  {
    asset: "LIV Indigo",
    apartmentNumber: 1002,
    bedrooms: 1,
    bathrooms: 2,
    parking: 1,
    floorSize: "66m2",
    altitude: "Top ",
  },
  {
    apartmentNumber: 2032,
    asset: "LIV Indigo",
    bedrooms: 1,
    bathrooms: 2,
    parking: 1,
    floorSize: "56m2",
    altitude: "Mid",
  },
  {
    asset: "LIV Indigo",
    apartmentNumber: 3002,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    floorSize: "63m2",
    altitude: "Top ",
  },
  {
    apartmentNumber: 4032,
    asset: "LIV Indigo",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    floorSize: "56m2",
    altitude: "Mid",
  },
  {
    asset: "LIV Indigo",
    apartmentNumber: 5002,
    bedrooms: 1,
    bathrooms: 3,
    parking: 1,
    floorSize: "36m2",
    altitude: "Top ",
  },
  {
    apartmentNumber: 6032,
    asset: "LIV Indigo",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    floorSize: "55m2",
    altitude: "Mid",
  },
  {
    asset: "LIV Munro",
    apartmentNumber: 1002,
    bedrooms: 1,
    bathrooms: 2,
    parking: 1,
    floorSize: "66m2",
    altitude: "Top ",
  },
  {
    apartmentNumber: 2032,
    asset: "LIV Munro",
    bedrooms: 1,
    bathrooms: 2,
    parking: 1,
    floorSize: "56m2",
    altitude: "Mid",
  },
  {
    asset: "LIV Munro",
    apartmentNumber: 3002,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    floorSize: "63m2",
    altitude: "Top ",
  },
  {
    apartmentNumber: 4032,
    asset: "LIV Munro",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    floorSize: "56m2",
    altitude: "Mid",
  },
  {
    asset: "LIV Munro",
    apartmentNumber: 5002,
    bedrooms: 1,
    bathrooms: 3,
    parking: 1,
    floorSize: "36m2",
    altitude: "Top ",
  },
  {
    apartmentNumber: 6032,
    asset: "LIV Munro",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    floorSize: "55m2",
    altitude: "Mid",
  },
  {
    apartmentNumber: 6032,
    asset: "LIV Munro",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    floorSize: "55m2",
    altitude: "Mid",
  },
];

module.exports = {
  assets,
  apartments,
};
